# -*- coding: utf-8 -*-
#
# This file is part of SENAITE.DATABOX
#
# Copyright 2018 by it's authors.


NOT_ADDABLE_TYPES = [
    "ARImport",
    "ARReport",
    "ARTemplate",
    "ARTemplates",
    "Analysis",
    "AnalysisCategories",
    "AnalysisCategory",
    "AnalysisProfile",
    "AnalysisProfiles",
    # "AnalysisRequest",
    "AnalysisRequestsFolder",
    "AnalysisService",
    "AnalysisServices",
    "AnalysisSpec",
    "AnalysisSpecs",
    "Attachment",
    "AttachmentType",
    "AttachmentTypes",
    "AutoImportLog",
    "Batch",
    "BatchFolder",
    "BatchLabel",
    "BatchLabels",
    "BikaCache",
    "BikaSetup",
    # "Calculation",
    "Calculations",
    # "Client",
    "ClientFolder",
    "Collection",
    # "Contact",
    "Container",
    "ContainerType",
    "ContainerTypes",
    "Containers",
    "DataBox",
    "DataBoxFolder",
    "Department",
    "Departments",
    "Document",
    "DuplicateAnalysis",
    "Event",
    "File",
    "Folder",
    "IdentifierType",
    "IdentifierTypes",
    "Image",
    # "Instrument",
    "InstrumentCalibration",
    "InstrumentCertification",
    "InstrumentLocation",
    "InstrumentLocations",
    "InstrumentMaintenanceTask",
    "InstrumentScheduledTask",
    "InstrumentType",
    "InstrumentTypes",
    "InstrumentValidation",
    "Instruments",
    "Invoice",
    "InvoiceBatch",
    "InvoiceFolder",
    "LabContact",
    "LabContacts",
    "LabProduct",
    "LabProducts",
    "Laboratory",
    "Link",
    "Manufacturer",
    "Manufacturers",
    "Method",
    "Methods",
    "Multifile",
    "News Item",
    "Preservation",
    "Preservations",
    "Pricelist",
    "PricelistFolder",
    "ReferenceAnalysis",
    "ReferenceDefinition",
    "ReferenceDefinitions",
    "ReferenceSample",
    "ReferenceSamplesFolder",
    "ReflexRule",
    "ReflexRuleFolder",
    "RejectAnalysis",
    "Report",
    "ReportFolder",
    "SRTemplate",
    "SRTemplates",
    "Sample",
    "SampleCondition",
    "SampleConditions",
    "SampleMatrices",
    "SampleMatrix",
    "SamplePartition",
    "SamplePoint",
    "SamplePoints",
    "SampleType",
    "SampleTypes",
    "SamplesFolder",
    "SamplingDeviation",
    "SamplingDeviations",
    "SamplingRound",
    "SamplingRounds",
    "StorageLocation",
    "StorageLocations",
    "SubGroup",
    "SubGroups",
    "Supplier",
    "SupplierContact",
    "Suppliers",
    "SupplyOrder",
    "SupplyOrderFolder",
    "Topic",
    "Worksheet",
    "WorksheetFolder",
    "WorksheetTemplate",
    "WorksheetTemplates",
]
