# -*- coding: utf-8 -*-

PROJECTNAME = "senaite.databox"

TMP_FOLDER_KEY = "senaite.databox.tmp"

# NOTE; Visible types are commented
NON_QUERYABLE_TYPES = [
    # "ARReport",
    # "ARTemplate",
    "ARTemplates",
    "ATBooleanCriterion",
    "ATCurrentAuthorCriterion",
    "ATDateCriteria",
    "ATDateRangeCriterion",
    "ATListCriterion",
    "ATPathCriterion",
    "ATPortalTypeCriterion",
    "ATReferenceCriterion",
    "ATRelativePathCriterion",
    "ATSelectionCriterion",
    "ATSimpleIntCriterion",
    "ATSimpleStringCriterion",
    "ATSortCriterion",
    # "AetiologicAgent",
    "AetiologicAgents",
    # "Analysis",
    "AnalysisCategories",
    # "AnalysisCategory",
    # "AnalysisProfile",
    "AnalysisProfiles",
    # "AnalysisRequest",
    "AnalysisRequestsFolder",
    # "AnalysisService",
    "AnalysisServices",
    # "AnalysisSpec",
    "AnalysisSpecs",
    # "Attachment",
    # "AttachmentType",
    "AttachmentTypes",
    "AuditLog",
    "AutoImportLog",
    # "Batch",
    "BatchFolder",
    # "BatchLabel",
    "BatchLabels",
    "BikaSetup",
    # "Calculation",
    "Calculations",
    # "CaseOutcome",
    "CaseOutcomes",
    # "CaseStatus",
    "CaseStatuses",
    # "CaseSyndromicClassification",
    "CaseSyndromicClassifications",
    # "Client",
    "ClientFolder",
    # "Contact",
    # "Container",
    # "ContainerType",
    "ContainerTypes",
    "Containers",
    # "DataBox",
    "DataBoxFolder",
    # "Department",
    "Departments",
    # "Disease",
    "Diseases",
    # "Doctor",
    "Doctors",
    "Document",
    # "Drug",
    # "DrugProhibition",
    "DrugProhibitions",
    "Drugs",
    # "DuplicateAnalysis",
    # "DynamicAnalysisSpec",
    "DynamicAnalysisSpecs",
    "Ethnicities",
    # "Ethnicity",
    "Event",
    "File",
    "Folder",
    # "IdentifierType",
    "IdentifierTypes",
    "Image",
    # "Immunization",
    "Immunizations",
    # "Instrument",
    "InstrumentCalibration",
    # "InstrumentCertification",
    # "InstrumentLocation",
    "InstrumentLocations",
    # "InstrumentMaintenanceTask",
    # "InstrumentScheduledTask",
    # "InstrumentType",
    "InstrumentTypes",
    # "InstrumentValidation",
    "Instruments",
    "InsuranceCompanies",
    # "InsuranceCompany",
    # "Invoice",
    # "LabContact",
    "LabContacts",
    # "LabProduct",
    "LabProducts",
    "Laboratory",
    "Link",
    # "Manufacturer",
    "Manufacturers",
    # "Method",
    "Methods",
    # "Multifile",
    "News Item",
    # "Patient",
    "Patients",
    "Plone Site",
    # "Preservation",
    "Preservations",
    # "Pricelist",
    "PricelistFolder",
    # "ReferenceAnalysis",
    # "ReferenceDefinition",
    "ReferenceDefinitions",
    # "ReferenceSample",
    "ReferenceSamplesFolder",
    # "ReflexRule",
    "ReflexRuleFolder",
    "RejectAnalysis",
    # "Report",
    "ReportFolder",
    # "SampleCondition",
    "SampleConditions",
    "SampleMatrices",
    # "SampleMatrix",
    # "SamplePoint",
    "SamplePoints",
    # "SampleType",
    "SampleTypes",
    # "SamplingDeviation",
    "SamplingDeviations",
    # "StorageContainer",
    # "StorageFacility",
    # "StorageLocation",
    "StorageLocations",
    "StorageRootFolder",
    "StorageSamplesContainer",
    # "SubGroup",
    "SubGroups",
    # "Supplier",
    "SupplierContact",
    "Suppliers",
    # "SupplyOrder",
    "SupplyOrderFolder",
    # "Symptom",
    "Symptoms",
    "TempFolder",
    "Topic",
    # "Treatment",
    "Treatments",
    # "VaccinationCenter",
    "VaccinationCenterContact",
    "VaccinationCenters",
    # "Worksheet",
    "WorksheetFolder",
    # "WorksheetTemplate",
    "WorksheetTemplates",
]
